### ISSUE TITLE
Blish HUD MP Repo + Docs

### ISSUE THREAD

**Issue by dlamkins** [Nexrym/Nexploration#1]
Just wanted to say hello as we've seen your pack shared around quite a bit - nice work!

We've added it to our auto linter, FYI, so if you push any future releases, you can check this page for any issues that we may detect (such as syntax issues, etc.).  It auto updates every 30 or so minutes.

https://mp-repo.blishhud.com/Nexploration.taco.html

And, if you decide to take advantage of any Blish HUD specific attributes or are looking for better attribute documentation somewhere, we've got a ton of it here on our site:
https://blishhud.com/docs/markers/development/attributes

You can close - just wanted to pass the info along in case it helped at all.  👍

**Comment by Nexrym** [comment]
Thanks for the kind words, and I will definitely be taking advantage of some of the Blish HUD specific attributes now that I've had the chance to look through the docs a bit.

Should be updating the pack within the next few days, so it'll be neat to have the Blish attributes implemented and functioning for the additional markers. Cheers!
